pub const NUMERALS: [&str; 13] = [
    "Zeroth", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten",
    "Eleven", "Twelve",
];

pub const ORDINALS: [&str; 13] = [
    "zero", "first", "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth", "ninth",
    "tenth", "eleventh", "twelfth",
];

pub const NOUNS: [&str; 40] = [
    "bottles",
    "cows",
    "servers",
    "pants",
    "snowflakes",
    "towels",
    "commas",
    "cats",
    "dogs",
    "bulbs",
    "texts",
    "leaves",
    "newspapers",
    "balls",
    "jugs",
    "socks",
    "bags",
    "bars",
    "donkeys",
    "sticks",
    "snails",
    "drums",
    "furs",
    "lamps",
    "skies",
    "windows",
    "pictures",
    "sofas",
    "boots",
    "cars",
    "trees",
    "cones",
    "trucks",
    "trunks",
    "tomatoes",
    "apples",
    "bananas",
    "plates",
    "planes",
    "wins",
];

pub const ADJECTIVES: [&str; 20] = [
    "blue",
    "harsh",
    "strange",
    "viable",
    "interesting",
    "hairy",
    "mellow",
    "weird",
    "sexy",
    "bizarre",
    "funny",
    "rubbery",
    "light",
    "leafy",
    "glowing",
    "glassy",
    "windy",
    "watery",
    "smelly",
    "exciting",
];
